baseURL = 'https://example.org/'
locale = 'en-us'
title = 'PCIU BBA-A CENTER'


# nabvar
[menus]
  [[menus.main]]
    name = "Home"
    url = "/"
    weight = 10

  [[menus.main]]
    name = "upload"
    url = "/upload/"
    weight = 20

  [[menus.main]]
    name = "About"
    url = "/about/"
    weight = 30

#   [[menus.main]]
#     name = "Contact"
#     url = "/contact/"
#     weight = 40
#     [menus.main.params]
#       is_button = true



# parameters

[params]
  # Navbar Customization
  logoLight = "images/Logo.png"
  logoDark = "images/Logo.png"  # Optional: If your logo needs high contrast on dark backgrounds
  logoHeight = "32px"                # Control height easily from configuration

# build scripts
[build]
  [build.buildStats]
    enable = true
  [[build.cachebusters]]
    source = 'assets/notwatching/hugo_stats\.json'
    target = 'css'
  [[build.cachebusters]]
    source = '(postcss|tailwind)\.config\.js'
    target = 'css'

[module]
  [[module.mounts]]
    source = 'assets'
    target = 'assets'
  [[module.mounts]]
    disableWatch = true
    source = 'hugo_stats.json'
    target = 'assets/notwatching/hugo_stats.json'